pipeline{
    agent{
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
    }
    parameters {
        choice(name: 'command', choices: ['Apply', 'Destroy'], description: 'Pick something')
    }
    stages{
        stage('init'){
            sh 'terraform init -reconfigure'
        }
        stage('plan'){
            sh 'terraform plan'
        }
        stage('apply'){
            input {
                message "Should we continue with apply command?"
                ok "Yes, we should."
            }
            when {
                expression { ${param.choice} == "Apply"}
            }
            sh 'terraform apply -auto-approve'
        }
        stage('destroy'){
            input {
                message "Should we continue with destroy command?"
                ok "Yes, we should."
            }
            when {
                expression { ${param.choice} == "Destroy"}
            }
            sh 'terraform destroy -auto-approve'
        }
    }
    post{
        success{

        }
        failure{

        }
        always{
            deleteDir()
        }
    }
}