pipeline{
    
    agent {
        label 'AGENT-1'
    }

    options{
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
        retry(2)
    }

    environment{
        DEPLOY_TO = 'DEV'
        GREETING = 'Good Morning' 
    }

    parameters{
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }

    stages{
        stage('Build'){
            steps{
                echo "Hello from Build"
            }
        }
        stage('Test'){
            steps{
                echo "Hello from Test"
            }
        }
        stage('Deploy'){
            steps{
                echo "Hello from Deploy"
            }
        }
        stage('Print Parameters') {
            steps{
                echo "Hello ${params.PERSON}"
                echo "Biography: ${params.BIOGRAPHY}"
                echo "Toggle: ${params.TOGGLE}"
                echo "Choice: ${params.CHOICE}"
                echo "Password: ${params.PASSWORD}"
            }
            }
    }

    post{
        always{
            echo 'I will run always'
        }
        success{
            echo 'I will run when pipeline is success'
        }
        failure{
            echo 'I will run when pipeline is failure'
        }
    }
}